spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    eureka:
      client:
        serviceUrl:
          defaultZone: http://10.251.22.28:8761  # Assuming your Eureka server is named 'eureka-server' in Docker Compose
        registerWithEureka: false
        fetchRegistry: true

server:
  port: 8080