services:
  eureka-server:
    image: ygqygq2/eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - acme

  order-service:
    build: ./order-service
    env_file:
      - ./order-service/.env
    ports:
      - "${PORT:-5004}:${PORT:-5004}"
    depends_on:
      - eureka-server
    networks:
      - acme

  inventory-service:
    build: ./inventory-service
    ports:
      - "5002:5002"
    environment:
      - INVENTORY_PORT=5002
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://10.251.22.28:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - acme

  user-service:
    build: ./user-service
    ports:
      - "5003:5003"
    environment:
      - USER_PORT=5003
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://10.251.22.28:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - acme

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - acme

networks:
  acme:
